---
GGOs:
  councildistricts:
  - Council Districy 1
  - Council Districy 2
contests:
  - name: state representative
    tally: plurality
    candidates:
      Up Down: partyA
      Left Right: partyB
      write-in: true
  - name:  state senate
    tally: plurality
    candidates:
      Cold Hot: partyA
      Pink Blue: partyB
    write-in: true
  - name: mayor
    tally: rcv
    candidates:
      Mary Roberts: partyA
      Robert Mary: partyB
      Jane Doe: partyB
      John Doe: partyC
      Tom Jones: partyC
    write-in: true
  - name: alderman ward 1
    tally: rcv
    candidates:
      Q One: partyC
      W Two: partyC
      e Foo: partyC
    write-in: true
  - name: alderman ward 2
    tally: rcv
    candidates:
      Q One: partyC
      W Two: partyC
      e Foo: partyC
    write-in: true
  - name : alderman ward 3
    tally: rcv
    candidates:
      Q Bbb: partyC
      W Ccc: partyC
      e Ddd: partyC
    write-in: true
  - name: Question 1 - school budget override
    tally: plurity
    question:
    - yes
    - no
  - name: Question 2 - new firehouse land purchase
    tally: two thirds majority
    question:
    - yes
    - no
vote centers:
  Emeryville Senior Center:
    address: 4321 Salem St, Emeryville, CA
    id: 000001
submodules: []
