---
contests:
  School Board:
    tally: rcv
    candidates:
      Hans Solo: partyB
      Someone Else: PartyC
  School Superintendent:
    tally: rcv
    candidates:
      Tommy: partyA
      111 222: partyB
submodules: []
