---
contests:
  US house:
    tally: rcv
    candidates:
      One Two: partyA
      Three Four: partyA
      Five Six: partyB
    write-in: false
GGOs:
  SchoolDistricts:
    - Alameda USD
    - Berkeley USD
    - Milpitas USD
submodules: []
